---
title: "PNC Check Results"
author: "Filippo Gambarota"
date: "4/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Packages

library(tidyverse)

# Loading Data

dat <- read.csv("calibration_data/csv/S1.txt") %>% 
  tibble()
```

# Overall dataset

```{r}
nrow(dat)

dat %>% 
  group_by(trial_type) %>% 
  summarise(n = n())
```

# Catch trials

```{r}
dat %>% 
  filter(trial_type == 0) %>% 
  group_by(pas) %>% 
  summarise(n = n())
```

# PAS

```{r}
# PAS distribution

dat %>% 
  ggplot(aes(x = pas, fill = gender)) +
  geom_bar() +
  facet_wrap(~emotion) +
  cowplot::theme_minimal_grid()
```



# Critical trials

```{r}

# 0 resp for valid trials

dat %>% 
  filter(pas == 0 & trial_type == 1)

```

# Staircase results

```{r}

# with catch

dat %>% 
  filter(trial_type != 99) %>% 
  ggplot(data = ., aes(x = trial, y = log(noise), color = as.factor(pas))) +
  geom_line(aes(group = 0), col = "black", size = 0.8) +
  geom_point(size = 5) +
  cowplot::theme_minimal_grid()

# without catch

dat %>% 
  filter(trial_type == 1) %>% 
  ggplot(aes(x = trial, y = noise, color = as.factor(pas))) +
  geom_hline(yintercept = dat$noise_est[1]) +
  geom_line(aes(group = 0), col = "black", size = 0.8) +
  geom_point(size = 5) +
  cowplot::theme_minimal_grid()

```

# Emotion

```{r}
dat %>% 
  filter(pas > 1) %>% 
  mutate(acc = ifelse((emotion == "fear" & emo_resp == 1) | (emotion == "neutral" & emo_resp == 0),
                      1, 0)) %>% 
  summarise(tot = n(),
            correct_emo = sum(acc),
            wrong_emo = tot - correct_emo,
            acc = mean(acc))
```

